# Build exe:
name: Build Executable for Windows

on:
  workflow_dispatch:

jobs:
  build-sea:
    name: Build Executable for Windows
    runs-on: windows-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: npm ci

      - name: Build application codes
        run: npm run build:bundle --workspace @gent-js/gent-sea

      - name: Build SEA blob
        run: node --experimental-sea-config sea.config.json
        working-directory: packages/gent-sea

      - name: Copy Node.js binary
        run: node -e "require('fs').copyFileSync(process.execPath, 'dist/gent-win.exe')"
        working-directory: packages/gent-sea

      - name: Inject blob
        run: npx postject dist/gent-win.exe NODE_SEA_BLOB dist/gent.blob --sentinel-fuse NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2
        working-directory: packages/gent-sea

      - name: Upload executable artifact
        uses: actions/upload-artifact@v4
        with:
          name: gent-win
          path: packages/gent-sea/dist/gent-win.exe
          retention-days: 1
      
      - name: checks
        run: echo "GITHUB_REF_NAME is $GITHUB_REF_NAME"

      - name: checks
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release list

      - name: checks
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release view "$GITHUB_REF_NAME"
      
      - name: checks
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release view "v0.1.15"

      - name: checks
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release view "v0.1.17"
      
      - name: Upload to GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload v0.1.19 packages/gent-sea/dist/gent-win.exe --clobber
